In [11]:
import numpy as np

dim = 4
array1 = np.arange(dim*dim).reshape(dim,dim)
print(array1)

for i in range(dim):
    print(array1[:,i])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  4  8 12]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]
